apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reel-content-worker
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      serviceAccountName: reel-content-worker@PROJECT_ID.iam.gserviceaccount.com
      containers:
        - image: gcr.io/PROJECT_ID/reel-content-worker:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: NODE_ENV
              value: production
            - name: APP_URL
              value: https://reel-content-worker-REGION.run.app
            - name: LLM_ENABLED
              value: "true"
          startupProbe:
            httpGet:
              path: /api/worker/generate
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/worker/generate
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
